### ISSUE TITLE
Relicense to Creative Commons(?)

### ISSUE THREAD

**Issue by MichaelAgarkov** [Cocoatwix/INTERNETCONNECTIVITYPORTAL#2]
Actually, the Mozilla Public License is for software, for a website there's Creative Commons licenses.

**Comment by Cocoatwix** [comment]
How do I change license?

**Comment by MichaelAgarkov** [comment]
> How do I change license?

I would just delete the license file and create a new one and save the license I would change it to in there.

**Comment by MichaelAgarkov** [comment]
Here's a website with all license agreements GitHub will show: https://choosealicense.com/appendix/

You can change it to the [Creative Commons Attribution Share Alike 4.0 International](https://choosealicense.com/licenses/cc-by-sa-4.0/), [Creative Commons Attribution 4.0 International](https://choosealicense.com/licenses/cc-by-4.0/) or the [Creative Commons Zero v1.0 Universal](https://choosealicense.com/licenses/cc0-1.0/). Choose the one you want. No pressure.

**Comment by Cocoatwix** [comment]
Cool, thanks! I'll push the new license tomorrow when I continue working on it
